version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - chore
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: markdownlint-cli
    versions:
    - 0.26.0
    - 0.27.0
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
